add makefile

diff --git a/Code/Working_Area/Makefile b/Code/Working_Area/Makefile
--- a/Code/Working_Area/Makefile
+++ b/Code/Working_Area/Makefile
@@ -1,12 +1,25 @@
-PYTHON = python3 #archive
-SCRIPT = main.py
+# Define variables
+SCRIPT = main.sh
 
-# Regla por defecto
+# Default rule
 all: execute
 
-# Regla para ejecutar el script
+# Rule to execute the script with an input file
 execute:
-	$(PYTHON) $(SCRIPT)
+	@if [ -z "$(pdb_complex)" ]; then \
+		echo "Error: You must provide an input file. Use: make INPUT=file.txt"; \
+		exit 1; \
+	fi
+	bash $(SCRIPT) $(pdb_complex)
+
+# Help rule
+help:
+	@echo "Input file must be provided as follows:"
+	@echo "  pdb_complex=file.pdb                          - Complex's input file"
+	@echo ""
+	@echo "Makefile Usage:"
+	@echo "  make execute pdb_complex=file.pdb             - Runs $(SCRIPT)"
+	@echo "  make help                                     - Displays this help message"
 
 # Regla para limpiar (si fuera necesario)
 clean:
